### ISSUE TITLE
Please provide more documentation for "ShellRun" script

### ISSUE THREAD

**Issue by llinfeng** [Lexikos/AutoHotkey-Release#1]
* The script: https://github.com/Lexikos/AutoHotkey-Release/blob/master/installer/source/Lib/ShellRun.ahk
* Problem: I am not able to send the following Command Line statement to AHK, through ShellRun: 
`"C:\Program Files\Mozilla Firefox\firefox.exe"  -new-instance -url "https://www.twitch.tv/directory/following" -url "https://www.twitter.com"
`
* My attempt does not get me anywhere: not even a window is started: `ShellRun("C:\Program Files\Mozilla Firefox\firefox.exe", "-new-instance -url 'https://www.twitch.tv/directory/following' -url 'https://www.twitter.com'")
`

Hope you could clarify the syntax for your `ShellRun` command.

**Comment by Lexikos** [comment]
If there was any documentation to provide, it would not be in this repository. Your request is misplaced.

The parameters are merely passed as-is to the IShellDispatch2.ShellExecute interface method, as shown in the code. You can find documentation on MSDN, or find help on the AutoHotkey forums.

**Comment by Elijas** [comment]
@llinfeng 

I've been searching documentation about `ShellRun` too when `ShellRun("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --new-window www.google.com")` didn't work, it turns out, parameters should have been provided as separate argument, just as is written in documentation:  `ShellRun("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", "--new-window www.google.com")`

In your case, you made a syntax error - you should not use single quotation mark symbols:
Bad:
`ShellRun("C:\Program Files\Mozilla Firefox\firefox.exe", "-new-instance -url 'https://www.twitch.tv/directory/following' -url 'https://www.twitter.com'")`
Good:
`ShellRun("C:\Program Files\Mozilla Firefox\firefox.exe", "-new-instance -url https://www.twitch.tv/directory/following -url https://www.twitter.com")`

The good version launches firefox for me with both sites open.
